import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { AdminShell } from "@/components/admin/AdminShell";
import { Loader2, RefreshCw, Download } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/_admin/files")({
  ssr: false,
  component: FilesPage,
});

type FileRow = {
  id: string; file_name: string; file_size: number | null;
  mime_type: string | null; file_path: string;
  created_at: string; submission_id: string | null;
};

const PAGE_SIZE = 50;

function FilesPage() {
  const [files, setFiles] = useState<FileRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);

  function load() {
    setLoading(true);
    // Only application-generated response exports belong here. Exports are
    // the rows the export pipeline inserts itself: submission_id AND
    // question_id are NULL and the object lives under exports/<form_id>/.
    // Respondent uploads can NEVER match — register_submission_file always
    // sets both ids and forces the path under the submission's own folder,
    // so even a respondent file renamed "*.xlsx" stays out of this list.
    supabase
      .from("submission_files")
      .select("id,file_name,file_size,mime_type,file_path,created_at,submission_id")
      .is("submission_id", null)
      .is("question_id", null)
      .like("file_path", "exports/%")
      .order("created_at", { ascending: false })
      .range(page * PAGE_SIZE, (page + 1) * PAGE_SIZE - 1)
      .then(({ data, error }) => {
        if (error) toast.error(error.message);
        setFiles((data ?? []) as FileRow[]);
        setLoading(false);
      });
  }

  useEffect(() => { load(); }, [page]);

  function formatBytes(n: number | null) {
    if (!n) return "—";
    if (n < 1024) return `${n} B`;
    if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
    return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  }

  // submission-files is a PRIVATE bucket — admin downloads go through
  // short-lived signed URLs (storage RLS: admin_all_submission_files).
  async function download(f: FileRow) {
    const { data, error } = await supabase.storage
      .from("submission-files")
      .createSignedUrl(f.file_path, 3600);
    if (error || !data?.signedUrl) {
      toast.error("Could not create a download link. Check storage policies (migration 005).");
      return;
    }
    window.open(data.signedUrl, "_blank", "noopener,noreferrer");
  }

  return (
    <AdminShell>
      <div className="p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold">Files</h1>
            <p className="text-sm text-muted-foreground">
              Response exports (.xlsx) generated by the app. Respondent uploads live with their submission in Responses.
            </p>
          </div>
          <button onClick={load} className="flex items-center gap-2 px-3 py-2 rounded-md border border-border text-sm hover:bg-secondary transition-colors">
            <RefreshCw className="h-4 w-4" /> Refresh
          </button>
        </div>

        {loading ? (
          <div className="flex justify-center py-12"><Loader2 className="animate-spin text-muted-foreground" /></div>
        ) : files.length === 0 && page === 0 ? (
          <div className="rounded-xl border border-border/60 bg-card p-12 text-center text-muted-foreground text-sm">
            No exports yet. Open a form's Responses page and click Export to generate one.
          </div>
        ) : (
          <div className="rounded-xl border border-border/60 bg-card overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/60 bg-secondary/30">
                  <th className="text-left px-4 py-2.5 font-semibold text-xs text-muted-foreground">FILE NAME</th>
                  <th className="text-left px-4 py-2.5 font-semibold text-xs text-muted-foreground">FORMAT</th>
                  <th className="text-left px-4 py-2.5 font-semibold text-xs text-muted-foreground">SIZE</th>
                  <th className="text-left px-4 py-2.5 font-semibold text-xs text-muted-foreground">EXPORTED</th>
                  <th className="text-right px-4 py-2.5 font-semibold text-xs text-muted-foreground">ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {files.map((f, i) => (
                  <tr key={f.id} className={`border-b border-border/30 ${i % 2 === 0 ? "" : "bg-secondary/10"}`}>
                    <td className="px-4 py-2.5 text-xs font-medium">{f.file_name}</td>
                    <td className="px-4 py-2.5">
                      {/* Everything here is an app-generated export — a badge
                          beats the unreadable full MIME string. */}
                      <span className="inline-flex items-center px-2 py-0.5 rounded-md text-[10px] font-semibold uppercase tracking-wide bg-green-500/15 text-green-500 border border-green-500/25">
                        XLSX
                      </span>
                    </td>
                    <td className="px-4 py-2.5 text-xs text-muted-foreground">{formatBytes(f.file_size)}</td>
                    <td className="px-4 py-2.5 text-xs text-muted-foreground whitespace-nowrap">
                      {new Date(f.created_at).toLocaleString()}
                    </td>
                    <td className="px-4 py-2.5 text-right">
                      <button onClick={() => download(f)}
                        className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs border border-border hover:bg-secondary transition-colors">
                        <Download className="h-3 w-3" /> Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="flex items-center justify-between px-4 py-3 border-t border-border/60">
              <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0}
                className="px-3 py-1 rounded text-sm border border-border hover:bg-secondary disabled:opacity-40">← Prev</button>
              <span className="text-xs text-muted-foreground">Page {page + 1}</span>
              <button onClick={() => setPage(p => p + 1)} disabled={files.length < PAGE_SIZE}
                className="px-3 py-1 rounded text-sm border border-border hover:bg-secondary disabled:opacity-40">Next →</button>
            </div>
          </div>
        )}
      </div>
    </AdminShell>
  );
}
