/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewResponseReferenceIdRouteImport } from './routes/view-response/$referenceId'
import { Route as FormsSlugRouteImport } from './routes/forms/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSystemHealthRouteImport } from './routes/_admin/system-health'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminProfileRouteImport } from './routes/_admin/profile'
import { Route as AdminFilesRouteImport } from './routes/_admin/files'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAuditRouteImport } from './routes/_admin/audit'
import { Route as AdminFormsIndexRouteImport } from './routes/_admin/forms/index'
import { Route as AdminFormsNewRouteImport } from './routes/_admin/forms/new'
import { Route as AdminFormsFormIdThemeRouteImport } from './routes/_admin/forms/$formId/theme'
import { Route as AdminFormsFormIdEditRouteImport } from './routes/_admin/forms/$formId/edit'
import { Route as AdminFormsFormIdResponsesIndexRouteImport } from './routes/_admin/forms/$formId/responses/index'
import { Route as AdminFormsFormIdResponsesSubmissionIdRouteImport } from './routes/_admin/forms/$formId/responses/$submissionId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewResponseReferenceIdRoute = ViewResponseReferenceIdRouteImport.update({
  id: '/view-response/$referenceId',
  path: '/view-response/$referenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsSlugRoute = FormsSlugRouteImport.update({
  id: '/forms/$slug',
  path: '/forms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFilesRoute = AdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsIndexRoute = AdminFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsNewRoute = AdminFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsFormIdThemeRoute = AdminFormsFormIdThemeRouteImport.update({
  id: '/forms/$formId/theme',
  path: '/forms/$formId/theme',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsFormIdEditRoute = AdminFormsFormIdEditRouteImport.update({
  id: '/forms/$formId/edit',
  path: '/forms/$formId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsFormIdResponsesIndexRoute =
  AdminFormsFormIdResponsesIndexRouteImport.update({
    id: '/forms/$formId/responses/',
    path: '/forms/$formId/responses/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminFormsFormIdResponsesSubmissionIdRoute =
  AdminFormsFormIdResponsesSubmissionIdRouteImport.update({
    id: '/forms/$formId/responses/$submissionId',
    path: '/forms/$formId/responses/$submissionId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AdminAuditRoute
  '/dashboard': typeof AdminDashboardRoute
  '/files': typeof AdminFilesRoute
  '/profile': typeof AdminProfileRoute
  '/settings': typeof AdminSettingsRoute
  '/system-health': typeof AdminSystemHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/view-response/$referenceId': typeof ViewResponseReferenceIdRoute
  '/forms/new': typeof AdminFormsNewRoute
  '/forms/': typeof AdminFormsIndexRoute
  '/forms/$formId/edit': typeof AdminFormsFormIdEditRoute
  '/forms/$formId/theme': typeof AdminFormsFormIdThemeRoute
  '/forms/$formId/responses/$submissionId': typeof AdminFormsFormIdResponsesSubmissionIdRoute
  '/forms/$formId/responses/': typeof AdminFormsFormIdResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AdminAuditRoute
  '/dashboard': typeof AdminDashboardRoute
  '/files': typeof AdminFilesRoute
  '/profile': typeof AdminProfileRoute
  '/settings': typeof AdminSettingsRoute
  '/system-health': typeof AdminSystemHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/view-response/$referenceId': typeof ViewResponseReferenceIdRoute
  '/forms/new': typeof AdminFormsNewRoute
  '/forms': typeof AdminFormsIndexRoute
  '/forms/$formId/edit': typeof AdminFormsFormIdEditRoute
  '/forms/$formId/theme': typeof AdminFormsFormIdThemeRoute
  '/forms/$formId/responses/$submissionId': typeof AdminFormsFormIdResponsesSubmissionIdRoute
  '/forms/$formId/responses': typeof AdminFormsFormIdResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/files': typeof AdminFilesRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/system-health': typeof AdminSystemHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/forms/$slug': typeof FormsSlugRoute
  '/view-response/$referenceId': typeof ViewResponseReferenceIdRoute
  '/_admin/forms/new': typeof AdminFormsNewRoute
  '/_admin/forms/': typeof AdminFormsIndexRoute
  '/_admin/forms/$formId/edit': typeof AdminFormsFormIdEditRoute
  '/_admin/forms/$formId/theme': typeof AdminFormsFormIdThemeRoute
  '/_admin/forms/$formId/responses/$submissionId': typeof AdminFormsFormIdResponsesSubmissionIdRoute
  '/_admin/forms/$formId/responses/': typeof AdminFormsFormIdResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/files'
    | '/profile'
    | '/settings'
    | '/system-health'
    | '/admin/login'
    | '/auth/callback'
    | '/forms/$slug'
    | '/view-response/$referenceId'
    | '/forms/new'
    | '/forms/'
    | '/forms/$formId/edit'
    | '/forms/$formId/theme'
    | '/forms/$formId/responses/$submissionId'
    | '/forms/$formId/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/files'
    | '/profile'
    | '/settings'
    | '/system-health'
    | '/admin/login'
    | '/auth/callback'
    | '/forms/$slug'
    | '/view-response/$referenceId'
    | '/forms/new'
    | '/forms'
    | '/forms/$formId/edit'
    | '/forms/$formId/theme'
    | '/forms/$formId/responses/$submissionId'
    | '/forms/$formId/responses'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/audit'
    | '/_admin/dashboard'
    | '/_admin/files'
    | '/_admin/profile'
    | '/_admin/settings'
    | '/_admin/system-health'
    | '/admin/login'
    | '/auth/callback'
    | '/forms/$slug'
    | '/view-response/$referenceId'
    | '/_admin/forms/new'
    | '/_admin/forms/'
    | '/_admin/forms/$formId/edit'
    | '/_admin/forms/$formId/theme'
    | '/_admin/forms/$formId/responses/$submissionId'
    | '/_admin/forms/$formId/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FormsSlugRoute: typeof FormsSlugRoute
  ViewResponseReferenceIdRoute: typeof ViewResponseReferenceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view-response/$referenceId': {
      id: '/view-response/$referenceId'
      path: '/view-response/$referenceId'
      fullPath: '/view-response/$referenceId'
      preLoaderRoute: typeof ViewResponseReferenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$slug': {
      id: '/forms/$slug'
      path: '/forms/$slug'
      fullPath: '/forms/$slug'
      preLoaderRoute: typeof FormsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/system-health': {
      id: '/_admin/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/files': {
      id: '/_admin/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AdminFilesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/forms/': {
      id: '/_admin/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AdminFormsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/forms/new': {
      id: '/_admin/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof AdminFormsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/forms/$formId/theme': {
      id: '/_admin/forms/$formId/theme'
      path: '/forms/$formId/theme'
      fullPath: '/forms/$formId/theme'
      preLoaderRoute: typeof AdminFormsFormIdThemeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/forms/$formId/edit': {
      id: '/_admin/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof AdminFormsFormIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/forms/$formId/responses/': {
      id: '/_admin/forms/$formId/responses/'
      path: '/forms/$formId/responses'
      fullPath: '/forms/$formId/responses/'
      preLoaderRoute: typeof AdminFormsFormIdResponsesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/forms/$formId/responses/$submissionId': {
      id: '/_admin/forms/$formId/responses/$submissionId'
      path: '/forms/$formId/responses/$submissionId'
      fullPath: '/forms/$formId/responses/$submissionId'
      preLoaderRoute: typeof AdminFormsFormIdResponsesSubmissionIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFilesRoute: typeof AdminFilesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminFormsNewRoute: typeof AdminFormsNewRoute
  AdminFormsIndexRoute: typeof AdminFormsIndexRoute
  AdminFormsFormIdEditRoute: typeof AdminFormsFormIdEditRoute
  AdminFormsFormIdThemeRoute: typeof AdminFormsFormIdThemeRoute
  AdminFormsFormIdResponsesSubmissionIdRoute: typeof AdminFormsFormIdResponsesSubmissionIdRoute
  AdminFormsFormIdResponsesIndexRoute: typeof AdminFormsFormIdResponsesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFilesRoute: AdminFilesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminFormsNewRoute: AdminFormsNewRoute,
  AdminFormsIndexRoute: AdminFormsIndexRoute,
  AdminFormsFormIdEditRoute: AdminFormsFormIdEditRoute,
  AdminFormsFormIdThemeRoute: AdminFormsFormIdThemeRoute,
  AdminFormsFormIdResponsesSubmissionIdRoute:
    AdminFormsFormIdResponsesSubmissionIdRoute,
  AdminFormsFormIdResponsesIndexRoute: AdminFormsFormIdResponsesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FormsSlugRoute: FormsSlugRoute,
  ViewResponseReferenceIdRoute: ViewResponseReferenceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
